version: '3.7'
services:
    postgres_dwh:
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRESQL_USERNAME=my_user
          - POSTGRESQL_PASSWORD=my_password
          - POSTGRESQL_DATABASE=dwh
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - "8432:5432"
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
          - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
          - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
        networks:
            dwh-network:
                ipv4_address: 172.123.0.33

networks: 
  dwh-network:
    external: true
